FROM node:20-alpine AS deps
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/types/package.json ./packages/types/package.json
COPY apps/dashboard/package.json ./apps/dashboard/package.json

RUN pnpm install --frozen-lockfile

FROM node:20-alpine AS builder
RUN corepack enable

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/dashboard/node_modules ./apps/dashboard/node_modules
COPY --from=deps /app/packages/types/node_modules ./packages/types/node_modules

COPY packages/types ./packages/types
COPY apps/dashboard ./apps/dashboard

WORKDIR /app/apps/dashboard

RUN rm -f .env .env.*

RUN pnpm build

FROM node:20-alpine as runner
RUN corepack enable

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/dashboard/next.config.* ./apps/dashboard/
COPY --from=builder /app/apps/dashboard/package.json ./apps/dashboard/
COPY --from=builder /app/apps/dashboard/.next ./apps/dashboard/.next
# COPY --from=builder /app/apps/dashboard/public ./apps/dashboard/public

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/dashboard/node_modules ./apps/dashboard/node_modules
COPY --from=builder /app/packages/types ./packages/types

COPY --from=deps /app/package.json ./package.json
COPY --from=deps /app/pnpm-workspace.yaml ./pnpm-workspace.yaml

EXPOSE ${PORT:-3000}

WORKDIR /app/apps/dashboard

CMD ["pnpm", "start"]